ALTER TABLE properties
ALTER COLUMN address SET NOT NULL,
ALTER COLUMN city SET NOT NULL,
ALTER COLUMN zip SET NOT NULL,
ALTER COLUMN state SET NOT NULL,
ALTER COLUMN status SET DEFAULT NULL,
ALTER COLUMN price SET DEFAULT NULL,
ALTER COLUMN bathrooms SET DEFAULT NULL,
ALTER COLUMN full_bathrooms SET DEFAULT NULL,
ALTER COLUMN half_bathrooms SET DEFAULT NULL,
ALTER COLUMN three_fourths_bathrooms SET DEFAULT NULL,
ALTER COLUMN one_fourths_bathrooms SET DEFAULT NULL,
ALTER COLUMN stories SET DEFAULT NULL,
ALTER COLUMN bedrooms SET DEFAULT NULL,
ALTER COLUMN parcel_number SET DEFAULT NULL,
ALTER COLUMN year_built SET DEFAULT NULL,
ALTER COLUMN zoning SET DEFAULT NULL,
ALTER COLUMN lot_size SET DEFAULT NULL,
ALTER COLUMN structure_size SET DEFAULT NULL,
ALTER COLUMN interior_living_size SET DEFAULT NULL,
ALTER COLUMN parking_spaces SET DEFAULT NULL,
ALTER COLUMN garage_spaces SET DEFAULT NULL,
ALTER COLUMN covered_spaces SET DEFAULT NULL,
ALTER COLUMN fireplace_count SET DEFAULT NULL,
ALTER COLUMN home_type SET DEFAULT NULL,
ALTER COLUMN architectural_style SET DEFAULT NULL,
ALTER COLUMN basement SET DEFAULT NULL,
ALTER COLUMN hoa SET DEFAULT NULL,
ALTER COLUMN hoa_fee SET DEFAULT NULL,
ALTER COLUMN laundry SET DEFAULT NULL,
ALTER COLUMN foundation SET DEFAULT NULL,
ALTER COLUMN senior_community SET DEFAULT NULL,
ALTER COLUMN property_condition SET DEFAULT NULL;

ALTER TABLE tax_history
ALTER COLUMN year SET NOT NULL,
ALTER COLUMN assessment SET DEFAULT NULL,
ALTER COLUMN tax SET DEFAULT NULL,
ALTER COLUMN address SET NOT NULL,
ALTER COLUMN city SET NOT NULL,
ALTER COLUMN zip SET NOT NULL,
ALTER COLUMN state SET NOT NULL;

ALTER TABLE price_history
ALTER COLUMN date SET NOT NULL,
ALTER COLUMN event SET NOT NULL,
ALTER COLUMN price SET DEFAULT NULL,
ALTER COLUMN address SET NOT NULL,
ALTER COLUMN city SET NOT NULL,
ALTER COLUMN zip SET NOT NULL,
ALTER COLUMN state SET NOT NULL;

ALTER TABLE accessibility_features
ALTER COLUMN feature SET NOT NULL,
ALTER COLUMN address SET NOT NULL,
ALTER COLUMN city SET NOT NULL,
ALTER COLUMN zip SET NOT NULL,
ALTER COLUMN state SET NOT NULL;

ALTER TABLE additional_structures
ALTER COLUMN structure SET NOT NULL,
ALTER COLUMN address SET NOT NULL,
ALTER COLUMN city SET NOT NULL,
ALTER COLUMN zip SET NOT NULL,
ALTER COLUMN state SET NOT NULL;

ALTER TABLE amenities
ALTER COLUMN amenity SET NOT NULL,
ALTER COLUMN address SET NOT NULL,
ALTER COLUMN city SET NOT NULL,
ALTER COLUMN zip SET NOT NULL,
ALTER COLUMN state SET NOT NULL;

ALTER TABLE bathroom_features
ALTER COLUMN feature SET NOT NULL,
ALTER COLUMN address SET NOT NULL,
ALTER COLUMN city SET NOT NULL,
ALTER COLUMN zip SET NOT NULL,
ALTER COLUMN state SET NOT NULL;

ALTER TABLE bedroom_features
ALTER COLUMN feature SET NOT NULL,
ALTER COLUMN address SET NOT NULL,
ALTER COLUMN city SET NOT NULL,
ALTER COLUMN zip SET NOT NULL,
ALTER COLUMN state SET NOT NULL;

ALTER TABLE construction_materials
ALTER COLUMN material SET NOT NULL,
ALTER COLUMN address SET NOT NULL,
ALTER COLUMN city SET NOT NULL,
ALTER COLUMN zip SET NOT NULL,
ALTER COLUMN state SET NOT NULL;

ALTER TABLE cooling
ALTER COLUMN type SET NOT NULL,
ALTER COLUMN address SET NOT NULL,
ALTER COLUMN city SET NOT NULL,
ALTER COLUMN zip SET NOT NULL,
ALTER COLUMN state SET NOT NULL;

ALTER TABLE dining_features
ALTER COLUMN feature SET NOT NULL,
ALTER COLUMN address SET NOT NULL,
ALTER COLUMN city SET NOT NULL,
ALTER COLUMN zip SET NOT NULL,
ALTER COLUMN state SET NOT NULL;

ALTER TABLE exterior_features
ALTER COLUMN feature SET NOT NULL,
ALTER COLUMN address SET NOT NULL,
ALTER COLUMN city SET NOT NULL,
ALTER COLUMN zip SET NOT NULL,
ALTER COLUMN state SET NOT NULL;

ALTER TABLE family_features
ALTER COLUMN feature SET NOT NULL,
ALTER COLUMN address SET NOT NULL,
ALTER COLUMN city SET NOT NULL,
ALTER COLUMN zip SET NOT NULL,
ALTER COLUMN state SET NOT NULL;

ALTER TABLE fencing
ALTER COLUMN type SET NOT NULL,
ALTER COLUMN address SET NOT NULL,
ALTER COLUMN city SET NOT NULL,
ALTER COLUMN zip SET NOT NULL,
ALTER COLUMN state SET NOT NULL;

ALTER TABLE fireplace_features
ALTER COLUMN feature SET NOT NULL,
ALTER COLUMN address SET NOT NULL,
ALTER COLUMN city SET NOT NULL,
ALTER COLUMN zip SET NOT NULL,
ALTER COLUMN state SET NOT NULL;

ALTER TABLE flooring
ALTER COLUMN type SET NOT NULL,
ALTER COLUMN address SET NOT NULL,
ALTER COLUMN city SET NOT NULL,
ALTER COLUMN zip SET NOT NULL,
ALTER COLUMN state SET NOT NULL;

ALTER TABLE gas
ALTER COLUMN type SET NOT NULL,
ALTER COLUMN address SET NOT NULL,
ALTER COLUMN city SET NOT NULL,
ALTER COLUMN zip SET NOT NULL,
ALTER COLUMN state SET NOT NULL;

ALTER TABLE heating
ALTER COLUMN type SET NOT NULL,
ALTER COLUMN address SET NOT NULL,
ALTER COLUMN city SET NOT NULL,
ALTER COLUMN zip SET NOT NULL,
ALTER COLUMN state SET NOT NULL;

ALTER TABLE included_appliances
ALTER COLUMN appliance SET NOT NULL,
ALTER COLUMN address SET NOT NULL,
ALTER COLUMN city SET NOT NULL,
ALTER COLUMN zip SET NOT NULL,
ALTER COLUMN state SET NOT NULL;

ALTER TABLE interior_features
ALTER COLUMN feature SET NOT NULL,
ALTER COLUMN address SET NOT NULL,
ALTER COLUMN city SET NOT NULL,
ALTER COLUMN zip SET NOT NULL,
ALTER COLUMN state SET NOT NULL;

ALTER TABLE kitchen_features
ALTER COLUMN feature SET NOT NULL,
ALTER COLUMN address SET NOT NULL,
ALTER COLUMN city SET NOT NULL,
ALTER COLUMN zip SET NOT NULL,
ALTER COLUMN state SET NOT NULL;

ALTER TABLE lot_features
ALTER COLUMN feature SET NOT NULL,
ALTER COLUMN address SET NOT NULL,
ALTER COLUMN city SET NOT NULL,
ALTER COLUMN zip SET NOT NULL,
ALTER COLUMN state SET NOT NULL;

ALTER TABLE parking
ALTER COLUMN type SET NOT NULL,
ALTER COLUMN address SET NOT NULL,
ALTER COLUMN city SET NOT NULL,
ALTER COLUMN zip SET NOT NULL,
ALTER COLUMN state SET NOT NULL;

ALTER TABLE patio_porch_details
ALTER COLUMN detail SET NOT NULL,
ALTER COLUMN address SET NOT NULL,
ALTER COLUMN city SET NOT NULL,
ALTER COLUMN zip SET NOT NULL,
ALTER COLUMN state SET NOT NULL;

ALTER TABLE pool_features
ALTER COLUMN feature SET NOT NULL,
ALTER COLUMN address SET NOT NULL,
ALTER COLUMN city SET NOT NULL,
ALTER COLUMN zip SET NOT NULL,
ALTER COLUMN state SET NOT NULL;

ALTER TABLE property_subtype
ALTER COLUMN type SET NOT NULL,
ALTER COLUMN address SET NOT NULL,
ALTER COLUMN city SET NOT NULL,
ALTER COLUMN zip SET NOT NULL,
ALTER COLUMN state SET NOT NULL;

ALTER TABLE roof
ALTER COLUMN type SET NOT NULL,
ALTER COLUMN address SET NOT NULL,
ALTER COLUMN city SET NOT NULL,
ALTER COLUMN zip SET NOT NULL,
ALTER COLUMN state SET NOT NULL;

ALTER TABLE services
ALTER COLUMN service SET NOT NULL,
ALTER COLUMN address SET NOT NULL,
ALTER COLUMN city SET NOT NULL,
ALTER COLUMN zip SET NOT NULL,
ALTER COLUMN state SET NOT NULL;

ALTER TABLE sewer
ALTER COLUMN type SET NOT NULL,
ALTER COLUMN address SET NOT NULL,
ALTER COLUMN city SET NOT NULL,
ALTER COLUMN zip SET NOT NULL,
ALTER COLUMN state SET NOT NULL;

ALTER TABLE spa_features
ALTER COLUMN feature SET NOT NULL,
ALTER COLUMN address SET NOT NULL,
ALTER COLUMN city SET NOT NULL,
ALTER COLUMN zip SET NOT NULL,
ALTER COLUMN state SET NOT NULL;

ALTER TABLE utilities
ALTER COLUMN utility SET NOT NULL,
ALTER COLUMN address SET NOT NULL,
ALTER COLUMN city SET NOT NULL,
ALTER COLUMN zip SET NOT NULL,
ALTER COLUMN state SET NOT NULL;

ALTER TABLE view_description
ALTER COLUMN description SET NOT NULL,
ALTER COLUMN address SET NOT NULL,
ALTER COLUMN city SET NOT NULL,
ALTER COLUMN zip SET NOT NULL,
ALTER COLUMN state SET NOT NULL;
